# This is a basic workflow to help you get started with Actions

name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version (e.g. 5.0.0B1 or 5.0.0)'
        type: string
        required: true

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}

jobs:
  release:
    name: Release
    uses: adaptris/interlok-release/.github/workflows/workflow-call-release.yml@main
    with:
      interlok-version: ${{ github.event.inputs.interlok-version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
