# This is a basic workflow to help you get started with Actions

name: Repository Dispatch Release

on:
  repository_dispatch:
    types: 
      - repository-dispatch-release

jobs:
  release:
    name: Release
    uses: adaptris/interlok-release/.github/workflows/workflow-call-release.yml@main
    with:
      release-version: ${{ github.event.client_payload.release-version }}
